version: "3.8"

services:
  tretton_db:
    image: mongo:latest
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - ./__MONGO_DATA__:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_USER_PASS}
    ports:
      - ${MONGO_EXPOSED_PORT}:27017
    networks:
      - tretton_network
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"

  tretton_server:
    build: server
    container_name: ${TRETTON_BACKEND}
    restart: always
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${TRETTON_BACKEND_PORT}:4010
    depends_on:
      - tretton_db
    links:
      - tretton_db
    networks:
      - tretton_network
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"

  tretton_client:
    build: client
    container_name: ${TRETTON_CLIENT}
    restart: always
    tty: true
    volumes:
      - ./client:/app
      - /app/node_modules/
    ports:
      - ${TRETTON_CLIENT_PORT}:3000
    depends_on:
      - tretton_db
      - tretton_server
    networks:
      - tretton_network
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"

networks:
  tretton_network:
